version: '3.6'

volumes:
  cargo-registry:

services:
  raft-engine:
    image: sawtooth-raft-engine:$ISOLATION_ID
    build:
      context: .
      dockerfile: Dockerfile-installed-${DISTRO}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      - 'http_proxy=${http_proxy}'
      - 'https_proxy=${https_proxy}'
      - 'no_proxy=${no_proxy}'
